### ISSUE TITLE
[RENAME] api URL, Restful 한 URL로 교체하기

### ISSUE THREAD

**Issue by LimGeon** [teampang/teampang_server#25]
**1. 소문자를 사용한다.** 
주소에서 대소문자를 구분하므로, 카멜방식이 아닌 소문자를 사용하여 작성한다.

_Bad_
http://restapi.example.com/users/postComments

_Good_
http://restapi.example.com/users/post-comments
.
.
.
**2. 언더바를 대신 하이픈을 사용한다.**
가급적 하이픈의 사용도 최소화하며, 정확한 의미나 표현을 위해 단어의 결합이 불가피한 경우에 사용한다.

_Bad_
http://restapi.example.com/users/post_comments

_Good_
http://restapi.example.com/users/post-comments
.
.
.
**3. 마지막에 슬래시를 포함하지 않는다.**
슬래시는 계층을 구분하는 것으로, 마지막에는 사용하지 않는다.

_Bad_
http://restapi.example.com/users/

_Good_
http://restapi.example.com/users

![image](https://user-images.githubusercontent.com/20794609/103412949-ee5cee00-4bba-11eb-84b7-8125311ab318.png)

.
.
.
**4. 행위는 포함하지 않는다.**
행위는 URL대신 Method를 사용하여 전달한다.(GET, POST, PUT, DELETE 등)

_Bad_
POST http://restapi.example.com/users/1/delete-post/1

_Good_
DELETE http://restapi.example.com/users/1/posts/1
.
.
.
출처: https://devuna.tistory.com/79 [튜나 개발일기📚]

**Comment by seungahkim** [comment]
3. 마지막에 슬래시를 포함하지 않는다.

아래 설정을 추가했습니다.

settings.py
```python
APPEND_SLASH = False
```
