### ISSUE TITLE
[FEAT] refresh token

### ISSUE THREAD

**Issue by seungahkim** [teampang/teampang_server#35]

**Comment by seungahkim** [comment]
#34 소셜로그인 확장을 고려하여 allauth를 사용했어요.
그런데 refresh token을 구현하기 위해서 JWT 를 사용

**Comment by seungahkim** [comment]
rest-auth 와 simplejwt 가 호환되지 않습니다.

**Comment by seungahkim** [comment]
로그아웃 했을 때!!!
```
{
    "detail": "Neither cookies or blacklist are enabled, so the token has not been deleted server side. Please make sure the token is deleted client side."
}
```
### 위 문제 해결 방안
- 토큰에 합리적인 만료 시간 설정

- 로그 아웃시 클라이언트 측에서 저장된 토큰 삭제

- 모든 승인 된 요청에 대해 블랙리스트 에 대해 제공된 토큰 쿼리

클라이언트에서 토큰 삭제 가능한가요?
@minseungseon @sanggae4133  @sumini97 
우선 만료시간을 1분정도로 짧게 설정해놓겠습니다.
현재: 5분

**Comment by minseungseon** [comment]
흠.. 한번 확인해보겠습니다! 
근데 그럼 새로운 토큰이 발급되면 그걸로 그냥 새로 토큰 할당하면 안될까요?
refresh token 이 들어왔으면 --> (프런트의)user.refreshtoken = 새로운 refreshtoken
