### ISSUE TITLE
[REFACTOR] .vscode/settings.json "python.pythonPath" 충돌 해결

### ISSUE THREAD

**Issue by blackstar0223** [teampang/teampang_server#41]
## Description

현재 settings.json에 "python.pythonPath"가 명시되어 있는데, 각자의 venv 환경에 따라 달라질 것 같습니다. 현재 상태로 유지 시 commit 마다 변경될 가능성...?이 있을 것 같아요.

해결방안:
1. settings.json을 gitignore (권장하지 않는 방법이라고 함)
2. settings.json을 커밋 시 add하지 않기
3. "python.pythonPath"를 settings.json에서 제거 후, 워크스페이스가 아닌 유저 setting에 추가

다른 좋은 방안들 코멘트 부탁드려요!

Reference: [StackOverflow](https://stackoverflow.com/questions/56825741/setting-the-python-path-for-local-project-in-vs-code-without-using-the-settings)

## Progress
- [x] 논의 후 한 가지 방안 결정
- [x] settings.json 변경

**Comment by seungahkim** [comment]
3번이 제일 적합한 것 같아요👍
