### ISSUE TITLE
[ERROR] createsuperuser 오류

### ISSUE THREAD

**Issue by blackstar0223** [teampang/teampang_server#45]
## Description

`python manage.py createsuperuser` 사용 시 아래 오류가 발생합니다:
`TypeError: CustomUser() got an unexpected keyword argument 'is_staff'`

<img width="900" alt="스크린샷 2021-01-24 오후 5 06 38" src="https://user-images.githubusercontent.com/58510013/105624689-11e82100-5e67-11eb-90b3-daaed1d6e782.png">

**Comment by seungahkim** [comment]
관리자가 장고 기본 유저모델이라서 오류가 나는 것 같아요!!
